version: '3.8'

services:

  redis:
    image: "redis:alpine"
    container_name: redis_container
    restart: always
    ports:
      - "6333:6333"

  fastapi_app:
    build: .
    container_name: fastapi_container
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      REDIS_URL: redis://redis:6333/0
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static


volumes:
  postgres_data: