version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis_container
    restart: always
    ports:
      - "6380:6379"  # Corrected Redis port
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  fastapi_app:
    build: .
    container_name: fastapi_container
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      REDIS_URL: redis://redis:6380/0  # Corrected Redis URL
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    depends_on:
      redis:
        condition: service_healthy  # Ensures Redis is ready before FastAPI starts

volumes:
  postgres_data:
