"""Updated table property

Revision ID: 2ffa0970edb7
Revises: 7c8a9c281e2e
Create Date: 2025-03-27 21:30:25.804726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ffa0970edb7'
down_revision: Union[str, None] = '7c8a9c281e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('standard_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('standards', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'standard_mapping')
    # ### end Alembic commands ###
