"""Updated table property

Revision ID: 7c8a9c281e2e
Revises: 2bc2b4086682
Create Date: 2025-03-27 21:09:38.217451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8a9c281e2e'
down_revision: Union[str, None] = '2bc2b4086682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standards', 'file')
    # ### end Alembic commands ###
